<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>IGoLibrary.Ex.Updater</AssemblyName>
    <RootNamespace>IGoLibrary.Ex.Updater</RootNamespace>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <OptimizationPreference>Size</OptimizationPreference>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\updater.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IGoLibrary.Ex.Updater.Core\IGoLibrary.Ex.Updater.Core.csproj" />
  </ItemGroup>
</Project>
